# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_messagelog_to_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_emails',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
